--1. 아래 조건에 테이블 생성
CREATE TABLE T_ITEM_LIST
(   
    no NUMBER(6),
    item_name VARCHAR2(24),
    price NUMBER(6),
    create_date DATE
)
;
2. 다음 조건에 맞는 시퀀스를 생성하시오.

CREATE SEQUENCE T_ITEM_LIST_PK_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999999;

3. 생성한 시퀀스의 값을 불러서 사용하는 방법을 작성하시오.

SELECT T_ITEM_LIST_PK_SEQ.NEXTVAL FROM DUAL;
SELECT T_ITEM_LIST_PK_SEQ.CURRVAL FROM DUAL;

4. 해당 시퀀스를 활용하여, 테이블에 INSERT 처리 하는 쿼리문을 작성하시오.

INSERT INTO T_ITEM_LIST VALUES(T_ITEM_LIST_PK_SEQ.NEXTVAL, 'A아이템', 3000, SYSDATE);
INSERT INTO T_ITEM_LIST VALUES(T_ITEM_LIST_PK_SEQ.NEXTVAL, 'B아이템', 24000, SYSDATE);
INSERT INTO T_ITEM_LIST VALUES(T_ITEM_LIST_PK_SEQ.NEXTVAL, 'C아이템', 54000, SYSDATE);
INSERT INTO T_ITEM_LIST VALUES(T_ITEM_LIST_PK_SEQ.NEXTVAL, 'D아이템', 42000, SYSDATE);

SELECT * FROM T_ITEM_LIST;