SELECT *
FROM STUDENT;

SELECT *
FROM DEPARTMENT;

SELECT S.NAME, S.DEPTNO1, D.DNAME
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO1= D.DEPTNO
AND S.DEPTNO1 = (SELECT DEPTNO1
                    FROM STUDENT
                    WHERE NAME = 'Anthony Hopkins'); 

SELECT DEPTNO1
FROM STUDENT
WHERE NAME = 'Anthony Hopkins';