SELECT 
    STUDNO,
    NAME,
    TO_CHAR(BIRTHDAY, 'YYYY-MM-DD') BIRTHDAY
FROM student --테이블의 정보 팝업설명 쉬프트 + 에프4
WHERE TO_CHAR(BIRTHDAY, 'MM')= '01'
;

SELECT 
    EMPNO,
    ENAME,
    HIREDATE HIREDATE
FROM emp
WHERE TO_CHAR(HIREDATE, 'MM') in ('01', '02', '03')
--WHERE TO_CHAR(HIREDATE, 'MM') == '01' OR
--WHERE TO_CHAR(HIREDATE, 'MM') == '02' OR
--WHERE TO_CHAR(HIREDATE, 'MM') == '03' 
;