--quiz

CREATE TABLE TABLE_DATA_1
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_DATA_2
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_COLC
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');

INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');

SELECT * FROM TABLE_DATA_1;

SELECT * FROM TABLE_DATA_2;

SELECT * FROM TABLE_COLC
ORDER BY STD_DATE;

--A업체 기준
MERGE INTO TABLE_COLC C
USING TABLE_DATA_1 D
ON (C.STD_DATE = D.CREATE_DATE)
WHEN MATCHED THEN --일치하면 업데이트
    UPDATE SET C.CHECK_DATA1 = 'Y'
WHEN NOT MATCHED THEN --일치하는게 없으면 추가
    INSERT VALUES (D.CREATE_DATE, 'Y', 'N');

--B업체 기준
MERGE INTO TABLE_COLC C
USING TABLE_DATA_2 D
ON (C.STD_DATE = D.CREATE_DATE)
WHEN MATCHED THEN --일치하면 업데이트
    UPDATE SET C.CHECK_DATA2 = 'Y'
WHEN NOT MATCHED THEN --일치하는게 없으면 추가
    INSERT VALUES (D.CREATE_DATE, 'N', 'Y');