CREATE TABLE T_MENU_12
(
    MENU_ID NUMBER PRIMARY KEY, --기본키라는게 PK 프라이머리 키 중복값 X, NULL X
    MENU_NAME VARCHAR2(128) NOT NULL,
        --CONSTRAINT t_menu NOT NULL,
    PRICE NUMBER(10),
    MENU_CG VARCHAR2(64),
    D_DATE DATE
);


INSERT INTO T_MENU_12(MENU_ID, MENU_NAME, PRICE, MENU_CG, D_DATE)
VALUES (1, '싸이버거', 6000, '완전식품', SYSDATE);

INSERT INTO T_MENU_12(MENU_ID, MENU_NAME, PRICE, MENU_CG, D_DATE)
VALUES (2, '콩나물비빔밥', 7000, '탄수화물', SYSDATE);

INSERT INTO T_MENU_12(MENU_ID, MENU_NAME, PRICE, MENU_CG, D_DATE)
VALUES (3, '닭가슴살', 3000, '단백질', SYSDATE);

INSERT INTO T_MENU_12(MENU_ID, MENU_NAME, PRICE, MENU_CG, D_DATE)
VALUES (4, '베트남쌀국수', 8000, '탄수화물', SYSDATE);

INSERT INTO T_MENU_12 --생략가능 전체 다 넣는경우
VALUES (5, '라면', 2000, '밀가루', SYSDATE);

SELECT *
FROM T_MENU_12;

--데이터 수정
UPDATE T_MENU_12
SET PRICE = 8500
--MENU_ID = 4; PK를 잡아서 써라!!!
WHERE PRICE = 8000;

--데이터 삭제
SELECT *
--DELETE
FROM T_MENU_12
WHERE PRICE = 2000;

COMMIT;