1. 다음 두 명령어는 어떤 기능을 수행하는 명령어인지 작성하고,
두 기능의 차이점이 있다면 설명하시오.
DELETE FROM 테이블명;
컬럼을 포함한 테이블을 전체 삭제. 데이터삭제 / WHERE 조건 특정데이터 COMMIT/ROLLBACK OK
TRUNCATE TABLE 테이블명;
구분된 컬럼은 남기고 데이터 값만 삭제. / 통으로 데이터 삭제 ROLLBACK 기회 X

SELECT *
FROM T_MEMBER_POINT; 

CREATE TABLE T_MEMBER_POINT
(   
    id NUMBER(6),
    no NUMBER(6),
    m_id VARCHAR(24) NOT NULL,
    score NUMBER(3),
    s_date DATE DEFAULT SYSDATE
        CONSTRAINT T_MEMBER_POINT_pk PRIMARY KEY (id, no)
);

CREATE SEQUENCE T_MEMBER_POINT_PK_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 999999
nocycle
;

INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '가이름'), '가이름', 88, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '나이름'), '나이름', 90, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '다이름'), '다이름', 55, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '라이름'), '라이름', 82, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '가이름'), '가이름', 88, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '나이름'), '나이름', 76, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '다이름'), '다이름', 99, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '라이름'), '라이름', 85, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '가이름'), '가이름', 90, SYSDATE);
INSERT INTO T_MEMBER_POINT VALUES(T_MEMBER_POINT_PK_SEQ.NEXTVAL,(SELECT NVL( MAX(NO), 0)+1 FROM T_MEMBER_POINT WHERE m_id = '라이름'), '라이름', 44, SYSDATE);


SELECT T_MEMBER_POINT_PK_SEQ.CURRVAL FROM DUAL;