--seq01

CREATE TABLE SEQ_TEST
(
    no NUMBER(3) PRIMARY KEY,
    name VARCHAR2(32)
);

SELECT * FROM SEQ_TEST;

--보고 수동으로 저장
INSERT INTO seq_test VALUES(1, '가이름');
--다음 가입자 이름 '나이름' 저장
INSERT INTO seq_test VALUES(2, '나이름');

--서브쿼리로 갯수 활용
SELECT COUNT(*) FROM SEQ_TEST; --현재저장된 갯수
SELECT COUNT(*)+1 FROM SEQ_TEST; --다음 저장할 차례 값

INSERT INTO SEQ_TEST VALUES((SELECT COUNT(*)+1 FROM SEQ_TEST), '다이름');
INSERT INTO SEQ_TEST VALUES((SELECT COUNT(*)+1 FROM SEQ_TEST), '라이름');
INSERT INTO SEQ_TEST VALUES((SELECT COUNT(*)+1 FROM SEQ_TEST), '마이름');

--테이블 관리
    --데이터 삭제로 관리하는 테이블
    SELECT * FROM SEQ_TEST;
    -- 다 탈퇴 -> 삭제
    DELETE FROM SEQ_TEST
    WHERE NO = 7;

INSERT INTO SEQ_TEST VALUES((SELECT COUNT(*)+1 FROM SEQ_TEST), '바이름');

--서브쿼리로 갯수 -> NO PK 값을 따져보고 활용
SELECT NO FROM SEQ_TEST; --PK로 따지겠다.
SELECT MAX(NO) FROM SEQ_TEST; --제일 큰 PK 값
SELECT MAX(NO)+1 FROM SEQ_TEST; --제일 큰 PK 값 다음 값

INSERT INTO SEQ_TEST VALUES((SELECT MAX(NO)+1 FROM SEQ_TEST), '바이름');

SELECT * FROM SEQ_TEST;

INSERT INTO SEQ_TEST VALUES((SELECT MAX(NO)+1 FROM SEQ_TEST), '사이름');
INSERT INTO SEQ_TEST VALUES((SELECT MAX(NO)+1 FROM SEQ_TEST), '아이름');

DELETE FROM SEQ_TEST;

INSERT INTO SEQ_TEST VALUES((SELECT MAX(NO)+1 FROM SEQ_TEST), '자이름');

SELECT NVL(MAX(NO), 0)+1 FROM SEQ_TEST;

INSERT INTO SEQ_TEST VALUES( (SELECT NVL( MAX(NO), 0)+1 FROM SEQ_TEST), '자이름');

INSERT INTO SEQ_TEST VALUES( (SELECT NVL( MAX(NO), 0)+1 FROM SEQ_TEST), '차이름');

    DELETE FROM SEQ_TEST
    WHERE NO = 2;

INSERT INTO SEQ_TEST VALUES( (SELECT NVL( MAX(NO), 0)+1 FROM SEQ_TEST), '카이름');
INSERT INTO SEQ_TEST VALUES( (SELECT NVL( MAX(NO), 0)+1 FROM SEQ_TEST), '타이름');

--
순차적으로 중복되지 않는 값을 사용 -> 시퀀스

CREATE SEQUENCE SEQ_TEST_PK_SEQ --시퀀스 등록
INCREMENT BY 1 --증가 값
START WITH 1 --시작 번호
MINVALUE 1 -- 다시 시작하는 번호
MAXVALUE 10 --끝 번호
CYCLE -- 번호 반복
CACHE 5;
--(CACHE 20)

DROP SEQUENCE SEQ_TEST_PK_SEQ; --시퀀스 삭제

시퀀스명.NEXTVAL --다음값 호출(사용)
시퀀스명.CURRVAL --현재값 확인

SELECT SEQ_TEST_PK_SEQ.NEXTVAL FROM DUAL; --다음값 호출(사용)
SELECT SEQ_TEST_PK_SEQ.CURRVAL FROM DUAL; --현재값 확인

CREATE SEQUENCE SEQ_TEST_PK_SEQ --시퀀스 등록
INCREMENT BY 1
START WITH 1;
--MIN/MAX 체크 X
--NOCYCLE 기본
--CACHE 20 기본

SELECT * FROM SEQ_TEST;
--DELETE FROM SEQ_TEST;
            --테이블명              시퀀스명.다음값호출
INSERT INTO SEQ_TEST VALUES(SEQ_TEST_PK_SEQ.NEXTVAL, 'A이름'); --시퀀스 사용
INSERT INTO SEQ_TEST VALUES(SEQ_TEST_PK_SEQ.NEXTVAL, 'B이름');
INSERT INTO SEQ_TEST VALUES(SEQ_TEST_PK_SEQ.NEXTVAL, 'C이름');
INSERT INTO SEQ_TEST VALUES(SEQ_TEST_PK_SEQ.NEXTVAL, 'D이름');

SELECT * FROM USER_SEQUENCES; 

--시퀀스 값 확인
SELECT SEQ_TEST_PK_SEQ.CURRVAL FROM DUAL; 
--1이 될수 있도록 증가값을 변경
ALTER SEQUENCE SEQ_TEST_PK_SEQ INCREMENT BY -7;
ALTER SEQUENCE SEQ_TEST_PK_SEQ MINVALUE 0;
--시퀀스 1회 실행
SELECT SEQ_TEST_PK_SEQ.NEXTVAL FROM DUAL;
--다시 증가값 설정 변경
ALTER SEQUENCE SEQ_TEST_PK_SEQ INCREMENT BY 1;

--설정 완료 후 시퀀스 조회;
SELECT SEQ_TEST_PK_SEQ.NEXTVAL FROM DUAL;